version: "3"

services:

  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome-debug:3
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
    networks:
      - backend

networks:
  backend:
    driver: bridge